import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS } from '../../../core/theme/theme';

export default StyleSheet.create({
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: SPACING.lg,
        paddingBottom: 32,
    },
    stepItem: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    stepCircleContainer: {
        alignItems: 'center',
        width: 24,
        height: 24,
        position: 'relative',
    },
    stepCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepCircleDone: { backgroundColor: COLORS.white },
    stepCircleActive: { backgroundColor: 'rgba(255,255,255,0.3)', borderWidth: 2, borderColor: COLORS.white },
    stepCirclePending: { backgroundColor: 'rgba(255,255,255,0.1)' },
    stepNumber: { fontSize: 10, fontWeight: 'bold' },
    stepNumberActive: { color: COLORS.white },
    stepNumberPending: { color: 'rgba(255,255,255,0.4)' },
    stepLabel: {
        fontSize: 9,
        fontWeight: '600',
        position: 'absolute',
        top: 28,
        width: 80,
        left: -28,
        textAlign: 'center',
    },
    stepLabelDone: { color: 'rgba(255,255,255,0.8)' },
    stepLabelActive: { color: COLORS.white },
    stepLabelPending: { color: 'rgba(255,255,255,0.3)' },
    stepLine: {
        flex: 1,
        height: 1,
        marginHorizontal: 4,
    },
    stepLineDone: { backgroundColor: 'rgba(255,255,255,0.7)' },
    stepLinePending: { backgroundColor: 'rgba(255,255,255,0.15)' },
    roleCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderWidth: 2,
        borderColor: 'rgba(30, 92, 46, 0.12)',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        gap: 16,
    },
    roleCardActive: {
        borderColor: '#1E5C2E',
        backgroundColor: 'rgba(30, 92, 46, 0.05)',
    },
    roleTitle: { fontSize: 16, fontWeight: 'bold', color: '#1A2E1A', marginBottom: 2 },
    roleTitleActive: { color: '#1E5C2E' },
    roleSub: { fontSize: 12, color: '#6B7B6B', marginTop: 2 },
    roleCheck: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: 'rgba(30, 92, 46, 0.12)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    roleCheckActive: {
        backgroundColor: '#1E5C2E',
        borderColor: '#1E5C2E',
    },
    alertBox: {
        flexDirection: 'row',
        backgroundColor: '#FEF3C7',
        borderWidth: 1,
        borderColor: '#FDE68A',
        borderRadius: RADIUS.md,
        padding: SPACING.md,
        marginBottom: SPACING.lg,
    },
    alertText: {
        flex: 1,
        fontSize: 12,
        color: '#92400E',
        marginLeft: 8,
    },
    footer: {
        padding: SPACING.lg,
        backgroundColor: COLORS.white,
        borderTopWidth: 1,
        borderColor: '#E2E8F0',
    },
    successContainer: {
        alignItems: 'center',
        paddingVertical: SPACING.xl,
    },
    successIconBox: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#D1FAE5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: SPACING.lg,
    },
    successName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.greenDeep,
        marginBottom: SPACING.xl,
    },
    summaryBox: {
        width: '100%',
        backgroundColor: '#ECFDF5',
        borderWidth: 1,
        borderColor: '#A7F3D0',
        borderRadius: RADIUS.lg,
        padding: SPACING.md,
    },
    summaryTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#065F46',
        textTransform: 'uppercase',
        marginBottom: SPACING.md,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderColor: '#D1FAE5',
    },
    summaryLabel: { fontSize: 13, color: '#047857' },
    summaryValue: { fontSize: 13, fontWeight: '600', color: '#064E3B' },
    headerLangToggle: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        borderRadius: 16,
        padding: 2,
        alignItems: 'center',
        justifyContent: 'center',
        height: 32,
    },
    headerLangButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerLangButtonActive: {
        backgroundColor: '#FFFFFF',
    },
    headerLangText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    headerLangTextActive: {
        color: '#1E5C2E',
    },
});
