import { StyleSheet, Platform } from 'react-native';
import { FONTS, SHADOWS } from '../../../core/theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF7F0',
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'android' ? 24 : 12,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: '#E8E0CE',
    backgroundColor: '#FAF7F0',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: '#1E5C2E',
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 20,
    paddingHorizontal: 36,
  },
  stepCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E4E4E7',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  stepCircleActive: {
    backgroundColor: '#1E5C2E',
  },
  stepCircleCompleted: {
    backgroundColor: '#15803D',
  },
  stepNumber: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: '#71717A',
  },
  stepNumberActive: {
    color: '#FFFFFF',
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: '#E4E4E7',
    marginHorizontal: -4,
    zIndex: 1,
  },
  stepLineActive: {
    backgroundColor: '#15803D',
  },
  stepperLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
  },
  stepLabel: {
    flex: 1,
    textAlign: 'center',
    fontSize: 11,
    fontFamily: FONTS.regular,
    color: '#A1A1AA',
  },
  stepLabelActive: {
    fontFamily: FONTS.bold,
    color: '#18181B',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  pageTitle: {
    fontFamily: FONTS.bold,
    fontSize: 20,
    color: '#18181B',
    marginBottom: 20,
    marginTop: 8,
  },
  storageCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    padding: 16,
    marginBottom: 12,
    ...SHADOWS.sm,
  },
  storageIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storageInfo: {
    flex: 1,
    marginLeft: 16,
  },
  storageName: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#18181B',
    marginBottom: 4,
  },
  storageMeta: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: '#71717A',
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#71717A',
    marginBottom: 8,
  },
  input: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    fontSize: 14,
    fontFamily: FONTS.regular,
    color: '#18181B',
  },
  btnPrimary: {
    backgroundColor: '#1E5C2E',
    borderRadius: 12,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    ...SHADOWS.sm,
  },
  btnPrimaryText: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#FFFFFF',
  },
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    padding: 20,
    marginBottom: 16,
    ...SHADOWS.sm,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 12,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F4F5',
  },
  reviewLabel: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: '#71717A',
  },
  reviewValue: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#18181B',
  },
  calloutBox: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  calloutText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: '#065F46',
    lineHeight: 18,
  },
});
