import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS, RADIUS } from '../../../core/theme/theme';

export default StyleSheet.create({
  csDashboardHeader: {
    width: '100%',
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
    marginBottom: 20,
    ...SHADOWS.md,
  },
  csHeaderGradient: {
    padding: 20,
  },
  csHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  csHeaderTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  csHeaderLocation: {
    fontSize: 12,
    color: '#A8D5BA',
    marginTop: 4,
    fontWeight: '500',
  },
  csBellBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  csBellDot: {
    position: 'absolute',
    top: 10,
    right: 11,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.errorRed,
  },
  csSummaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  csSummaryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 12,
    ...SHADOWS.sm,
  },
  csSummaryCardLabel: {
    fontSize: 10,
    color: COLORS.textLight,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  csSummaryCardValue: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.greenDeep,
    marginTop: 6,
  },
  csSummaryCardSub: {
    fontSize: 10,
    color: COLORS.textLight,
    marginTop: 2,
    fontWeight: '500',
  },
  csSectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.greenDeep,
    marginVertical: 14,
    alignSelf: 'flex-start',
  },
  csGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    width: '100%',
    marginBottom: 20,
  },
  csGridItem: {
    width: '30%',
    aspectRatio: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.sm,
  },
  csGridIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  csGridLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textDark,
    textAlign: 'center',
  },
  csSectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  csViewAllText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.greenMid,
  },
  csActivityList: {
    width: '100%',
    gap: 12,
    marginBottom: 20,
  },
  csActivityCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.sm,
  },
  csActivityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  csActivityTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textDark,
  },
  csActivitySubtitle: {
    fontSize: 11,
    color: COLORS.textLight,
    marginTop: 2,
  },
  csActivityBadge: {
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  csActivityBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  csActivityMetaGrid: {
    flexDirection: 'row',
    backgroundColor: '#FAF8F3',
    borderRadius: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: '#F0EBE0',
  },
  csActivityMetaItem: {
    flex: 1,
    alignItems: 'center',
  },
  csActivityMetaDivider: {
    width: 1,
    backgroundColor: '#EAD9B0',
  },
  csActivityMetaLabel: {
    fontSize: 8,
    fontWeight: '600',
    color: COLORS.textLight,
    textTransform: 'uppercase',
  },
  csActivityMetaValue: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.greenDeep,
    marginTop: 2,
  },
});
