import { StyleSheet, Platform } from 'react-native';
import { FONTS, SHADOWS } from '../../../core/theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF7F0',
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'android' ? 24 : 12,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderColor: '#E8E0CE',
    backgroundColor: '#FAF7F0',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: '#1E5C2E',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  summaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    marginBottom: 20,
    gap: 12,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    paddingVertical: 12,
    alignItems: 'center',
    ...SHADOWS.sm,
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: FONTS.bold,
  },
  summaryLabel: {
    fontSize: 11,
    color: '#71717A',
    marginTop: 4,
    fontFamily: FONTS.regular,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 13,
    color: '#71717A',
    textAlign: 'center',
    marginTop: 12,
    fontFamily: FONTS.regular,
    lineHeight: 18,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F4F4F5',
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 12,
    ...SHADOWS.sm,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  idBadge: {
    backgroundColor: '#F4F4F5',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginRight: 8,
  },
  idText: {
    fontFamily: FONTS.mono,
    fontSize: 11,
    color: '#71717A',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
  rightHeader: {
    alignItems: 'flex-end',
  },
  weightText: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: '#18181B',
  },
  dateText: {
    fontSize: 11,
    color: '#71717A',
    marginTop: 2,
    fontFamily: FONTS.regular,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: FONTS.bold,
    color: '#18181B',
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 12,
    color: '#71717A',
    fontFamily: FONTS.regular,
    marginBottom: 12,
  },
  vehicleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F4F5',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
  },
  vehicleText: {
    fontFamily: FONTS.mono,
    fontSize: 12,
    color: '#18181B',
  },
  approveBtn: {
    backgroundColor: '#F59E0B',
    borderRadius: 12,
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  approveBtnText: {
    color: '#FFFFFF',
    fontFamily: FONTS.bold,
    fontSize: 13,
  },
  deliveredRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveredText: {
    color: '#047857',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
  transitRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  transitText: {
    color: '#1D4ED8',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: Platform.OS === 'ios' ? 34 : 16,
  },
  modalHeader: {
    backgroundColor: '#1E5C2E',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    fontFamily: FONTS.bold,
  },
  closeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBody: {
    padding: 20,
  },
  calloutBox: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FDE68A',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  calloutTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#92400E',
    fontFamily: FONTS.bold,
  },
  calloutSub: {
    fontSize: 12,
    color: '#B45309',
    marginTop: 4,
    fontFamily: FONTS.regular,
  },
  otpInstructions: {
    fontSize: 13,
    color: '#71717A',
    marginBottom: 16,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  otpInputRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    position: 'relative',
    gap: 8,
  },
  otpBox: {
    width: 44,
    height: 52,
    borderWidth: 2,
    borderColor: '#E4E4E7',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  otpBoxActive: {
    borderColor: '#1E5C2E',
  },
  otpCharText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E5C2E',
    fontFamily: FONTS.bold,
  },
  hiddenInput: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0,
  },
  submitBtn: {
    backgroundColor: '#1E5C2E',
    borderRadius: 12,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    ...SHADOWS.sm,
  },
  submitBtnText: {
    color: '#FFFFFF',
    fontFamily: FONTS.bold,
    fontSize: 14,
  },
});
