import { StyleSheet, Platform, StatusBar } from 'react-native';
import { SHADOWS, FONTS } from '../../../core/theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF7F0',
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 56,
    paddingBottom: 12,
    paddingHorizontal: 20,
    backgroundColor: '#FAF7F0',
  },
  topHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1B4332',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },

  // Red Balance Gradient Card
  balanceCard: {
    borderRadius: 20,
    padding: 20,
    ...SHADOWS.md,
    marginBottom: 16,
  },
  balanceLabel: {
    fontSize: 12,
    color: '#FEE2E2',
    fontWeight: '600',
  },
  balanceAmount: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    marginTop: 6,
  },
  balanceSub: {
    fontSize: 12,
    color: '#FEE2E2',
    marginTop: 4,
    fontWeight: '600',
  },
  cardActionsRow: {
    flexDirection: 'row',
    marginTop: 16,
    gap: 12,
  },
  btnStatement: {
    flex: 1,
    flexDirection: 'row',
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnStatementText: {
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  btnPay: {
    flex: 1.2,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOWS.sm,
  },
  btnPayText: {
    fontSize: 13,
    color: '#DC2626',
    fontWeight: '850',
  },

  // Total Charged & Paid Small Cards Row
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.sm,
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#777777',
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '850',
    color: '#1A1A1A',
    marginTop: 6,
  },

  // Section Header
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1B4332',
  },
  filterLink: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#777777',
  },

  // Ledger List Cards Block
  ledgerBlock: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.sm,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  ledgerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  rowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#F3EFE3',
  },
  rowTitle: {
    fontSize: 14,
    fontWeight: '750',
    color: '#1A1A1A',
  },
  rowDate: {
    fontSize: 11,
    color: '#777777',
    marginTop: 3,
  },
  rowAmount: {
    fontSize: 14,
    fontWeight: '800',
  },
  rowBalance: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(30, 64, 50, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '100%',
    maxWidth: 340,
    padding: 24,
    alignItems: 'center',
    ...SHADOWS.lg,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1E4032',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
  },
  modalButtonPrimary: {
    width: '100%',
    height: 48,
    borderRadius: 24,
    backgroundColor: '#1E4032',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    ...SHADOWS.sm,
  },
  modalButtonTextPrimary: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  backLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 4,
  },
  backLinkText: {
    fontSize: 14,
    color: '#2D6A4F',
    fontWeight: '700',
  },
  summaryPageTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1E4032',
    marginBottom: 20,
  },
  summaryDetailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    padding: 20,
    ...SHADOWS.md,
    marginBottom: 24,
  },
  summaryDetailItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3EFE3',
  },
  detailLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#777777',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  detailValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1A1A',
  },
  statusBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginTop: 4,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#B45309',
  },
  doneBtn: {
    width: '100%',
    minHeight: 52,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 26,
    backgroundColor: '#1E4032',
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOWS.md,
    marginBottom: 12,
  },
  doneBtnText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 20,
  },
  alreadyPaidBtn: {
    width: '100%',
    minHeight: 52,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 26,
    backgroundColor: '#F5EDD6',
    borderWidth: 1,
    borderColor: '#EAD9B0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 36,
  },
  alreadyPaidBtnText: {
    fontSize: 14,
    color: '#2D6A4F',
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 20,
  },
  headerLangToggle: {
    flexDirection: 'row',
    backgroundColor: '#EAF2EB',
    borderRadius: 16,
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
  },
  headerLangButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLangButtonActive: {
    backgroundColor: '#1E5C2E',
  },
  headerLangText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E5C2E',
  },
  headerLangTextActive: {
    color: '#FFFFFF',
  },

  // Form Styles for Verification
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E4032',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  formInput: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    fontSize: 14,
    color: '#1A1A1A',
  },
  uploadAreaContainer: {
    width: '100%',
    height: 120,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#2D6A4F',
    backgroundColor: '#F5EDD6',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  uploadAreaTextMain: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1E4032',
    textAlign: 'center',
    marginBottom: 4,
  },
  uploadAreaTextSub: {
    fontSize: 11,
    color: '#71717A',
    fontWeight: '600',
  },
  uploadedFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 64,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EAD9B0',
    backgroundColor: '#FAF7F0',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  uploadedFileName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  uploadedFileSub: {
    fontSize: 11,
    color: '#71717A',
    fontWeight: '500',
    marginTop: 2,
  },
  clearFileBtn: {
    padding: 6,
  },
  dateSelectorTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E4E4E7',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
  },
  dateSelectorText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  successIconWrapper: {
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1E4032',
    marginBottom: 8,
    textAlign: 'center',
  },
  successSubheading: {
    fontSize: 14,
    color: '#7A7A7A',
    textAlign: 'center',
    paddingHorizontal: 24,
    marginBottom: 24,
    lineHeight: 20,
  },

  // Custom Date Picker Modal Styles
  datePickerContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '90%',
    maxWidth: 320,
    padding: 24,
    alignItems: 'center',
    ...SHADOWS.lg,
  },
  datePickerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1E4032',
    marginBottom: 20,
  },
  datePickerSelectorsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 24,
  },
  datePickerCol: {
    alignItems: 'center',
    width: 64,
  },
  datePickerArrow: {
    padding: 6,
  },
  datePickerVal: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1A1A',
    marginVertical: 4,
  },
  datePickerColLabel: {
    fontSize: 11,
    color: '#71717A',
    fontWeight: '600',
  },
  datePickerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
    gap: 12,
  },
  datePickerCancelBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  datePickerCancelText: {
    fontSize: 14,
    color: '#71717A',
    fontWeight: '600',
  },
  datePickerConfirmBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#1E4032',
    borderRadius: 18,
  },
  datePickerConfirmText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  webHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'ios' ? 12 : 16,
    paddingBottom: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FAF7F0',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E2D9',
  },
  btnClosePayment: {
    marginRight: 16,
  },
  webHeaderTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E5C2E',
  },
  partialPayCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#EAD9B0',
    marginBottom: 16,
    ...SHADOWS.sm,
  },
  partialPayLeft: {
    flex: 1,
  },
  partialPayTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1B4332',
  },
  partialPaySub: {
    fontSize: 10,
    color: '#71717A',
    marginTop: 2,
  },
  partialPayRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  partialInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF8F3',
    borderWidth: 1,
    borderColor: '#EAD9B0',
    borderRadius: 10,
    paddingHorizontal: 8,
    height: 38,
    width: 90,
  },
  currencyPrefix: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1B4332',
    marginRight: 2,
  },
  partialTextInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: '#1B4332',
    paddingVertical: 0,
  },
  btnPayPartial: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E5C2E',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 38,
  },
  btnPayPartialText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
});
