import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS } from '../../../theme';

export default StyleSheet.create({
  filterSection: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    marginBottom: 16,
    ...SHADOWS.sm,
    gap: 12,
  },
  filterSectionLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.greenMid,
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  dropdownField: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF8F3',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#EAD9B0',
  },
  dropdownFieldDisabled: {
    opacity: 0.5,
  },
  dropdownIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F0EBE0',
  },
  dropdownFieldInner: {
    flex: 1,
    marginLeft: 12,
  },
  dropdownLabel: {
    fontSize: 10,
    color: COLORS.textLight,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dropdownValue: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textDark,
    marginTop: 2,
  },
  dropdownChevron: {
    fontSize: 18,
    color: COLORS.textLight,
    fontWeight: '300',
  },
  fetchActionBtn: {
    width: '100%',
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    backgroundColor: '#CCCCCC',
    position: 'relative',
    ...SHADOWS.md,
  },
  fetchActionBtnDisabled: {
    backgroundColor: '#E6E6E6',
    shadowOpacity: 0,
    elevation: 0,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  fetchActionBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    zIndex: 2,
  },
  priceDashboard: {
    width: '100%',
    borderRadius: 16,
    marginBottom: 20,
    overflow: 'hidden',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.md,
  },
  dashboardAccentBar: {
    height: 4,
    backgroundColor: COLORS.greenMid,
  },
  dashboardBody: {
    padding: 22,
  },
  dashboardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  cropIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F0F7F4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardIcon: {
    fontSize: 24,
  },
  dashboardTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1A1A1A',
    letterSpacing: 0.2,
  },
  dashboardLocation: {
    fontSize: 12,
    color: COLORS.textLight,
    fontWeight: '500',
    marginTop: 2,
  },
  dashboardDivider: {
    height: 1,
    backgroundColor: '#F3EFE3',
    marginVertical: 18,
  },
  priceCardsRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  spreadGaugeContainer: {
    marginTop: 8,
    backgroundColor: '#FAF8F3',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#F0EBE0',
  },
  spreadGaugeLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  spreadGaugeMin: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.greenMid,
  },
  spreadGaugeSpread: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.greenDeep,
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  spreadGaugeMax: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.amber,
  },
  spreadGaugeTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
    position: 'relative',
  },
});
