import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS } from '../../../core/theme/theme';

export default StyleSheet.create({
  farmerListCard: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    marginBottom: 12,
    ...SHADOWS.sm,
  },
  farmerListAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FAF5E8',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EAD9B0',
  },
  farmerListName: {
    fontSize: 15,
    fontWeight: '850',
    color: COLORS.greenDeep,
  },
  farmerListMeta: {
    fontSize: 11,
    color: COLORS.textLight,
    marginTop: 2,
    fontWeight: '500',
  },
  csPricesList: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.sm,
    marginBottom: 20,
  },
  csPriceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3EFE3',
  },
  csPriceName: {
    fontSize: 13,
    fontWeight: '750',
    color: COLORS.textDark,
  },
  csPriceLoc: {
    fontSize: 10,
    color: COLORS.textLight,
    marginTop: 1,
  },
  csPriceVal: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.greenDeep,
  },
  csPriceTrend: {
    fontSize: 9,
    fontWeight: '700',
    marginTop: 1,
  },
  // Search styles for farmer lookup
  searchContainer: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: COLORS.textDark,
    borderWidth: 1,
    borderColor: '#E8E0CE',
    ...SHADOWS.sm,
  },
  searchButton: {
    backgroundColor: COLORS.greenDeep,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
    ...SHADOWS.sm,
  },
  searchButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '700',
  },
});
