import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS, SPACING, RADIUS, SHADOWS } from '../../../core/theme/theme';

export const s = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAF7F0',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.wheatDark,
    backgroundColor: '#FAF7F0',
  },
  closeBtn: {
    padding: SPACING.sm,
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.greenDeep,
  },
  tabsContainer: {
    flexDirection: 'row',
    padding: SPACING.sm,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.wheatDark,
    justifyContent: 'space-between',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.sm,
    marginHorizontal: 2,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    backgroundColor: '#FAF7F0',
  },
  tabButtonActive: {
    backgroundColor: COLORS.greenDeep,
    borderColor: COLORS.greenDeep,
  },
  tabButtonText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.greenMid,
  },
  tabButtonTextActive: {
    color: COLORS.white,
  },
  scrollContent: {
    padding: SPACING.md,
  },
  contextCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.lg,
    ...SHADOWS.sm,
  },
  contextRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contextText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textDark,
  },
  fieldLabel: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.greenDeep,
    marginBottom: SPACING.sm,
    marginTop: SPACING.sm,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
    marginBottom: SPACING.md,
  },
  categoryPill: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    margin: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '45%',
    flexGrow: 1,
  },
  categoryPillActive: {
    backgroundColor: COLORS.greenDeep,
    borderColor: COLORS.greenDeep,
  },
  categoryPillText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.textDark,
  },
  categoryPillTextActive: {
    color: COLORS.white,
  },
  categoryPillSubText: {
    fontFamily: FONTS.regular,
    fontSize: 9,
    color: COLORS.textLight,
    marginTop: 2,
  },
  categoryPillSubTextActive: {
    color: COLORS.wheat,
  },
  input: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.md,
    paddingVertical: Platform.OS === 'ios' ? 12 : 8,
    paddingHorizontal: SPACING.md,
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: COLORS.textDark,
    marginBottom: SPACING.lg,
  },
  multilineInput: {
    height: 110,
  },
  submitBtn: {
    backgroundColor: COLORS.greenMid,
    borderRadius: RADIUS.lg,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.sm,
    ...SHADOWS.sm,
  },
  submitBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.white,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.wheatDark,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.xl,
    backgroundColor: '#FAF7F0',
  },
  loadingText: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.greenDeep,
    marginTop: SPACING.md,
  },
  subText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textMid,
    marginTop: 4,
  },
  successBadge: {
    marginBottom: SPACING.md,
  },
  successTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: COLORS.greenDeep,
    textAlign: 'center',
  },
  ticketIdText: {
    fontFamily: FONTS.mono,
    fontSize: 14,
    color: COLORS.amber,
    marginTop: SPACING.xs,
    marginBottom: SPACING.lg,
  },
  successCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    width: '100%',
    alignItems: 'center',
    marginBottom: SPACING.xl,
    ...SHADOWS.sm,
  },
  successInfoLabel: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textLight,
  },
  successInfoValue: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.textDark,
    marginTop: 2,
    marginBottom: SPACING.md,
  },
  successCardSub: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textMid,
    textAlign: 'center',
    lineHeight: 16,
  },
  doneBtn: {
    backgroundColor: COLORS.greenDeep,
    borderRadius: RADIUS.md,
    paddingVertical: 12,
    paddingHorizontal: SPACING.xl,
    minWidth: 150,
    alignItems: 'center',
    ...SHADOWS.sm,
  },
  doneBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.white,
  },
  errorBadge: {
    marginBottom: SPACING.md,
  },
  errorTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: COLORS.errorRed,
    textAlign: 'center',
  },
  errorDescription: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textMid,
    textAlign: 'center',
    marginTop: SPACING.sm,
    marginBottom: SPACING.lg,
    lineHeight: 18,
  },
  retryBtn: {
    backgroundColor: COLORS.amber,
    borderRadius: RADIUS.md,
    paddingVertical: 12,
    paddingHorizontal: SPACING.xl,
    minWidth: 150,
    alignItems: 'center',
    ...SHADOWS.sm,
  },
  retryBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.white,
  },
  cancelTextBtn: {
    marginTop: SPACING.lg,
    padding: SPACING.sm,
  },
  cancelTextBtnLabel: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textLight,
  },
  historyContent: {
    padding: SPACING.md,
  },
  historyTitle: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.greenDeep,
    marginBottom: SPACING.md,
  },
  noTicketsTitle: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: COLORS.textDark,
    marginTop: SPACING.sm,
  },
  noTicketsSub: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 4,
    textAlign: 'center',
  },
  ticketCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
    overflow: 'hidden',
    ...SHADOWS.sm,
  },
  ticketCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.md,
    justifyContent: 'space-between',
  },
  ticketIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.xs,
  },
  ticketCardId: {
    fontFamily: FONTS.mono,
    fontSize: 13,
    fontWeight: 'bold',
    color: COLORS.amber,
    marginRight: SPACING.sm,
  },
  statusBadge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: RADIUS.sm,
  },
  statusBadgeText: {
    fontSize: 9,
    fontFamily: FONTS.bold,
  },
  ticketCardSubject: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.textDark,
    marginBottom: 2,
  },
  ticketCardMeta: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: COLORS.textLight,
  },
  ticketCardExpanded: {
    padding: SPACING.md,
    backgroundColor: '#FDFBF7',
  },
  expandedSectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.greenMid,
    marginTop: SPACING.md,
    marginBottom: SPACING.sm,
  },
  originalDescriptionBox: {
    backgroundColor: '#F5EDD6',
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.sm,
    padding: SPACING.sm,
  },
  originalDescriptionText: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textDark,
    lineHeight: 16,
  },
  noConversationsText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textLight,
    padding: SPACING.sm,
    textAlign: 'center',
    lineHeight: 16,
  },
  conversationsContainer: {
    marginTop: SPACING.sm,
  },
  chatBubble: {
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    marginVertical: SPACING.xs,
    maxWidth: '85%',
  },
  chatBubbleUser: {
    backgroundColor: '#E8F5E9',
    borderColor: '#C8E6C9',
    borderWidth: 1,
    alignSelf: 'flex-end',
  },
  chatBubbleAgent: {
    backgroundColor: '#ECEFF1',
    borderColor: '#CFD8DC',
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  chatBubbleSender: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: COLORS.textLight,
    marginBottom: 2,
  },
  chatBubbleText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textDark,
    lineHeight: 15,
  },
  chatBubbleTime: {
    fontFamily: FONTS.mono,
    fontSize: 8,
    color: COLORS.textLight,
    alignSelf: 'flex-end',
    marginTop: 2,
  },
  attachmentList: {
    marginBottom: SPACING.md,
  },
  attachmentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    marginBottom: SPACING.xs,
    justifyContent: 'space-between',
  },
  attachmentName: {
    flex: 1,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.textDark,
  },
  removeAttachmentBtn: {
    padding: 4,
  },
  attachBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5EDD6',
    borderWidth: 1,
    borderColor: COLORS.wheatDark,
    borderRadius: RADIUS.md,
    paddingVertical: 12,
    marginBottom: SPACING.lg,
    borderStyle: 'dashed',
  },
  attachBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.greenDeep,
  },
  limitText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textLight,
    textAlign: 'center',
    marginBottom: SPACING.lg,
  },
});
