import { StyleSheet, Platform, StatusBar } from 'react-native';
import { FONTS } from '../../../core/theme/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF7F0',
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 12 : 56,
    paddingBottom: 12,
    paddingHorizontal: 20,
    backgroundColor: '#FAF7F0',
  },
  topHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  shieldIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    marginRight: 10,
  },
  brandTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1E5C2E',
    fontFamily: FONTS.bold,
  },
  searchIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(30, 92, 46, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchIconBtnActive: {
    backgroundColor: '#1E5C2E',
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E8F0',
    width: '100%',
  },
  filterForm: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderBottomWidth: 1,
    borderColor: '#E2E8F0',
  },
  filterFormTitle: {
    fontSize: 14,
    fontWeight: '750',
    color: '#1E5C2E',
    marginBottom: 14,
    fontFamily: FONTS.bold,
  },
  inputGroup: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#71717A',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  textInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
  },
  textInput: {
    flex: 1,
    fontSize: 13,
    color: '#18181B',
    paddingVertical: 0,
    fontFamily: FONTS.regular,
  },
  filterInputRow: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 10,
    padding: 10,
    justifyContent: 'center',
  },
  filterInputLabel: {
    fontSize: 10,
    color: '#71717A',
    textTransform: 'uppercase',
    fontWeight: '600',
    fontFamily: FONTS.regular,
    marginBottom: 2,
  },
  filterInputValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#18181B',
    fontFamily: FONTS.bold,
  },
  filterButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 6,
  },
  filterResetBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
  },
  filterResetBtnText: {
    fontSize: 12,
    color: '#71717A',
    fontFamily: FONTS.regular,
  },
  filterApplyBtn: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#1E5C2E',
    justifyContent: 'center',
  },
  filterApplyBtnText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
  tabContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    marginBottom: 16,
  },
  tabBg: {
    flexDirection: 'row',
    backgroundColor: '#F4F4F5',
    borderRadius: 12,
    padding: 4,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBtnActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#71717A',
    fontFamily: FONTS.regular,
  },
  tabTextActive: {
    color: '#18181B',
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
  cropFilterContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  cropScrollView: {
    gap: 8,
  },
  cropPill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  cropPillActive: {
    backgroundColor: '#1E5C2E',
    borderColor: '#1E5C2E',
  },
  cropPillText: {
    fontSize: 12,
    color: '#71717A',
    fontWeight: '500',
    fontFamily: FONTS.regular,
  },
  cropPillTextActive: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
  dateRefreshRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  dateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateText: {
    fontSize: 12,
    color: '#71717A',
    fontFamily: FONTS.regular,
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  refreshText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1E5C2E',
    fontFamily: FONTS.bold,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 16,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardLeft: {
    flex: 1,
  },
  cardCrop: {
    fontSize: 14,
    fontWeight: '700',
    color: '#18181B',
    fontFamily: FONTS.bold,
  },
  cardLocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  cardLocText: {
    fontSize: 12,
    color: '#71717A',
    fontFamily: FONTS.regular,
  },
  cardRight: {
    alignItems: 'flex-end',
  },
  cardPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#18181B',
    fontFamily: FONTS.mono,
  },
  trendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  trendText: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: FONTS.mono,
  },
  auctionMetaText: {
    fontSize: 11,
    color: '#71717A',
    marginTop: 4,
    fontFamily: FONTS.regular,
  },
  emptyCard: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 13,
    color: '#71717A',
    fontFamily: FONTS.regular,
  },
  errorCard: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderRadius: 16,
    padding: 24,
    marginTop: 20,
  },
  errorText: {
    fontSize: 13,
    color: '#B91C1C',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 18,
    fontFamily: FONTS.regular,
  },
  retryBtn: {
    backgroundColor: '#1E5C2E',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryBtnText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: FONTS.bold,
  },
});
