name: Hello Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    name: Print Hello Message
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello workflow successfull"
